[package]
name = "wiremock-grpc-proc-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.81"
quote = "1.0.10"
proc-macro2 = "1.0.32"
regex = "1.5.4"
cargo_toml = "0.10.1"
anyhow = "1.0.45"
log = "0.4.14"